Add the function to upload to tgraph
Rongronggg9/RSS-to-Telegram-Bot pull request #431
Opened 2024-03-11 02:47 UTC by zxcvbnmzsedr

Upload the image directly to tgraph without proxying through another site.

2024-03-11 02:51 UTC, Rongronggg9 commented on requirements.txt
> +requests==2.26.0
RSStT is asynchronous, using synchronous HTTP lib will make the bot stuck.
Use aiohttp instead.

2024-03-11 02:51 UTC, Rongronggg9 commented on src/env.py
> +TELEGRAPH_IMG_UPLOAD: Final = os.environ['TELEGRAPH_IMG_UPLOAD'] if os.environ.get('TELEGRAPH_IMG_UPLOAD') else False
Document it in `docs/advanced-settings.md`, `docker-compose.yml.sample` and `.env.smaple`.

2024-03-11 02:52 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +                            logger.warning(f'Processed img: {attr_content}')
Why warning?

2024-03-11 02:55 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +def telegraph_file_upload(file_url):
What if moving it to `src/web/media.py`?

2024-03-11 02:57 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +    error, txt-file can not be processed
Copied from elsewhere?

2024-03-11 03:02 UTC, zxcvbnmzsedr commented
No problem, I didn't consider that much; this way is the quickest and most straightforward solution to my current problem. I will make some adjustments to the code based on your advice.

2024-03-11 03:02 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +        upload_response = requests.post(url, files={'file': ('file', image_data)})
Write a POST wrapper in `src/web/req.py`, which shares most codes with `_get` and `get`, and use it here. Or else proxy and other features will not be applied.

2024-03-11 03:04 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +        # 提取图片内容
Unneeded comment. The code itself is self-describing.

2024-03-11 03:05 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> -
Unneeded reformatting.

2024-03-11 03:05 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> -
Ditto.

2024-03-11 03:05 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +    response = requests.get(file_url)
Use the `web.get` wrapper (in `src/web/req.py`). Or else proxy and other features will not be applied.

2024-03-11 03:32 UTC, Rongronggg9 requested changes
Personally, I do not object to the feature, as long as it is opt-in (it does be in the current revision). But it is more like a "dirty hack" as far as I can see now, so more polishing is needed before it can be merged.

2024-03-11 03:32 UTC, Rongronggg9 commented on requirements.txt
> +requests==2.26.0
RSStT is asynchronous, using synchronous HTTP lib will make the bot stuck.
Use the `web` wrapper (in `src/web/req.py`) instead.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/env.py
> +TELEGRAPH_IMG_UPLOAD: Final = os.environ['TELEGRAPH_IMG_UPLOAD'] if os.environ.get('TELEGRAPH_IMG_UPLOAD') else False
Document it in `docs/advanced-settings.md`, `docker-compose.yml.sample` and `.env.smaple`.
And use `__bool_parser()` above.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> -
Unneeded reformatting.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> -
Ditto.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +                            logger.warning(f'Processed img: {attr_content}')
Why warning?

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +    return construct_weserv_url(file_url)
What about moving it to `src/web/media.py`?

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +    error, txt-file can not be processed
Copied from else where?

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +    if response.status_code == 200:
Use the `web.get` wrapper (in `src/web/req.py`). Or else proxy and other features will not be applied.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +        # 提取图片内容
Unneeded comment. The code itself is self-describing.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +        upload_response = requests.post(url, files={'file': ('file', image_data)})
Write a POST wrapper in `src/web/req.py`, which shares most codes with `_get` and `get`, and use it here. Or else proxy and other features will not be applied.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +        url = 'https://telegra.ph/upload'
This should be a const variable outside the function.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +        telegraph_url = f'https://telegra.ph{telegraph_url}'
The domain of Telegraph should be a const variable outside the function.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +        telegraph_url = f'https://telegra.ph{telegraph_url}'
All three lines can be inlined into one line.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +    if response.status_code == 200:
Only using a condition is not sufficient. Exception handling (fallback) is needed.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +import json
Adding `import` should be done on hand. Do not rely on your IDE to do it.
Read the `import` blocks twice to see where to add `import`.

2024-03-11 03:32 UTC, Rongronggg9 commented on src/parsing/tgraph.py
> +import requests
Ditto.

2024-03-11 07:02 UTC, Rongronggg9 commented
Oh, I thought of a much more elegant solution for your use case just now.
Upload media to Telegraph via https://github.com/Rongronggg9/rsstt-img-relay so that it can be enabled for all users (opt-out).

For now, I am going to close your PR. I will implement the feature I mentioned above soon in the following weeks - you don't need to do anything further but just looking forward to it!

2024-03-11 07:02 UTC, closed without merging

2024-03-14 17:55 UTC, Rongronggg9 commented
> I will implement the feature I mentioned above soon in the following weeks

Such a feature has been implemented in https://github.com/Rongronggg9/rsstt-img-relay/commit/750210443882d2c35e5f4f92f50d0bdd748af4e2. E.g., `/upload_graph/https://example.com/example.jpg`.

The next step is to implement the corresponding feature in RSStT to take advantage of it.

2024-03-20 02:59 UTC, zxcvbnmzsedr commented
I found that tgraph has certain restrictions on uploaded media files, such as requiring the dimensions to be within 5000*4000, the file size to be less than 10MB, and not accepting webp images. Uploading images that do not meet these requirements will result in an error message "Image dimensions invalid". Would handling this in JS be very cumbersome?
@Rongronggg9

2024-03-20 03:13 UTC, Rongronggg9 commented
> Would handling this in JS be very cumbersome?

No need to actually "handle" it. All we need to do is to invoke images.weserv.nl on demand.

2024-03-27 17:55 UTC, Rongronggg9 commented
> All we need to do is to invoke [images.weserv.nl](https://images.weserv.nl/) on demand.

Done in https://github.com/Rongronggg9/rsstt-img-relay/commit/711597605b9797ade60c7cadc67e6a65ced3c157

2024-03-27 18:20 UTC, Rongronggg9 commented
> file size to be less than 10MB

The limit should be 5MiB.

> Image dimensions invalid

Reconsider the case, we'd better let it fail in order not to resize long images (words within them will become invisible after resizing).
If an image is not too long, it is very unlikely to hit the dimension limit before hitting the size limit. In other words, we should filter out the "Image dimensions invalid" error message, preventing it from causing images to be resized.

2024-03-28 15:56 UTC, Rongronggg9 commented
All done 🎉